# version: '3.8'

services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    volumes:
      - .:/app
    command: >
      sh -c "npm run server"
